# Generated by Django 5.2.17 on 2026-09-22 19:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A. Economic'), ('B', 'B. Educational'), ('C', 'C. Family'), ('D', 'D. Societal/Community'), ('E', 'E. Other')], max_length=1)),
                ('text', models.CharField(max_length=300)),
                ('is_reportable', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_days', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-6](,[0-6])*$', 'Use comma-separated weekdays, 0 (Monday) through 6 (Sunday).')])),
                ('meeting_time', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=7)),
                ('stopped_on', models.DateField(blank=True, null=True)),
                ('stopped_reason', models.TextField(blank=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reports.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reports.student')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=300)),
                ('attained_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainments', to='reports.goal')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_goals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='reports.student')),
            ],
            options={
                'ordering': ['-attained_on', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MonthLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_month_lock'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='valid_lock_month')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('TA', 'Tutor absent'), ('SA', 'Student absent'), ('H', 'Holiday')], default='HELD', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reports.assignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'date'), name='one_session_per_pairing_day'), models.CheckConstraint(condition=models.Q(models.Q(('hours__in', [Decimal('0.25'), Decimal('0.5'), Decimal('0.75'), Decimal('1'), Decimal('1.25'), Decimal('1.5'), Decimal('1.75'), Decimal('2'), Decimal('2.25'), Decimal('2.5'), Decimal('2.75'), Decimal('3'), Decimal('3.25'), Decimal('3.5'), Decimal('3.75'), Decimal('4'), Decimal('4.25'), Decimal('4.5'), Decimal('4.75'), Decimal('5'), Decimal('5.25'), Decimal('5.5'), Decimal('5.75'), Decimal('6'), Decimal('6.25'), Decimal('6.5'), Decimal('6.75'), Decimal('7'), Decimal('7.25'), Decimal('7.5'), Decimal('7.75'), Decimal('8')]), ('status', 'HELD')), models.Q(('hours', 0), ('status__in', ['TA', 'SA', 'H'])), _connector='OR'), name='valid_session_status_hours')],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tutor', 'student'), name='unique_active_pairing'),
        ),
        migrations.AddConstraint(
            model_name='studentgoal',
            constraint=models.UniqueConstraint(condition=models.Q(('goal__isnull', False)), fields=('student', 'goal'), name='unique_student_catalog_goal'),
        ),
        migrations.AddConstraint(
            model_name='studentgoal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_text', ''), ('goal__isnull', False)), models.Q(('goal__isnull', True), models.Q(('custom_text', ''), _negated=True)), _connector='OR'), name='catalog_or_custom_goal'),
        ),
    ]
